### PR TITLE
fix(build): sync-ts-config script needs import assertion of type json

### LINKED ISSUE #2163: fix(build): sync-ts-config script needs import assertion of type json
When the TS config syncing script is executed, it crashes like this: 

My NodeJS version is: `v16.14.2`

```sh
$ yarn sync-ts-config
yarn run v1.22.17
$ TS_NODE_PROJECT=tools/tsconfig.json node --experimental-json-modules --loader ts-node/esm ./tools/sync-npm-deps-to-tsc-projects.ts
(node:1049500) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
TypeError [ERR_IMPORT_ASSERTION_TYPE_MISSING]: Module "file:///.../cactus/lerna.json" needs an import assertion of type "json"
    at new NodeError (node:internal/errors:371:5)
    at validateAssertions (node:internal/modules/esm/assert:82:15)
    at defaultLoad (node:internal/modules/esm/load:24:3)
    at load (/.../cactus/node_modules/ts-node/src/esm.ts:257:43)
    at async ESMLoader.load (node:internal/modules/esm/loader:359:20)
    at async ESMLoader.moduleProvider (node:internal/modules/esm/loader:280:47) {
  code: 'ERR_IMPORT_ASSERTION_TYPE_MISSING'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### PR DESCRIPTION
**Pull request by aldousalvarez**
Fixes #2163

Signed-off-by: aldousalvarez <aldousss.alvarez@gmail.com>

### CODE REVIEW

**Review by takeutak — APPROVED** [review]

**Review by jagpreetsinghsasan — APPROVED** [review]

File: tools/sync-npm-deps-to-tsc-projects.ts [hunk 1]
```diff
@@ -5,8 +5,9 @@ import JSON5 from "json5";
 import fs from "fs-extra";
 import { globby, Options as GlobbyOptions } from "globby";
 import { RuntimeError } from "run-time-error";
-import lernaJson from "../lerna.json";
+import { readFileSync } from "fs";
 
+const lernaJson = JSON.parse(readFileSync("lerna.json", "utf8"));
```
Comment (petermetz) [inline tools/sync-npm-deps-to-tsc-projects.ts:10]: @aldousalvarez Please 
1. Move this logic to within the main function and make sure to

2. use the readFileAsync call instead so that we don't block (it doesn't make much of a difference in a very simple utility script like this but regardless best practices are like muscle memory so I advocate for adhereing to them even when it does not seem crucial to do so)

3. Make sure to parse the JSON file with an absolute path (e.g. leverage the already computed `PROJECT_DIR` variable)

**Review by petermetz — CHANGES_REQUESTED** [review]

File: tools/sync-npm-deps-to-tsc-projects.ts (hunk 1 above)
Comment (aldousalvarez) [reply tools/sync-npm-deps-to-tsc-projects.ts]: @petermetz already done with the latest commit. re-requested to review the changes made. Thank you so much

File: tools/sync-npm-deps-to-tsc-projects.ts [hunk 2]
```diff
@@ -19,16 +19,19 @@ const main = async (argv: string[], env: NodeJS.ProcessEnv) => {
...
   const TS_CONFIG = "tsconfig.json";
   const PACKAGE_JSON = "package.json";
+  const LERNA_JSON = "lerna.json";
   const SCRIPT_DIR = __dirname;
   const PROJECT_DIR = path.join(SCRIPT_DIR, "../");
   console.log(`SCRIPT_DIR=${SCRIPT_DIR}`);
   console.log(`PROJECT_DIR=${PROJECT_DIR}`);
-
-  const pkgJsonGlobPatterns = lernaJson.packages.map((it) =>
+  const lernaJson = JSON.parse(
```
Comment (petermetz) [inline tools/sync-npm-deps-to-tsc-projects.ts:27]: @aldousalvarez Looking much better now, thank you! Last nit-pick is to pull these two function calls out to their own lines so that it's easier to debug what crashed if all we have is that there was some exception thrown on a particular line.

**Review by petermetz — CHANGES_REQUESTED** [review]

File: tools/sync-npm-deps-to-tsc-projects.ts (hunk 2 above)
Comment (aldousalvarez) [reply tools/sync-npm-deps-to-tsc-projects.ts]: @petermetz Hello, already done with the latest [commit](https://github.com/hyperledger/cactus/pull/2164/commits/997eab68410e27442aaf01ffd4cc0bfb19cf683b). is this the two function calls that you mentioned that should be pulled out to their own? 

const pkgJsonGlobPatterns = lernaJson.packages.map((it: string) =>
  "./".concat(it).concat(`/${PACKAGE_JSON}`),
);

const tsConfigJsonGlobPatterns = lernaJson.packages.map((it: string) =>
  "./".concat(it).concat(`/${TS_CONFIG}`),
);

Comment (petermetz) [reply tools/sync-npm-deps-to-tsc-projects.ts]: @aldousalvarez No, I meant the function calls on the line that this comment is specifically attached to:
`const lernaJson = JSON.parse(await readFile(PROJECT_DIR + LERNA_JSON, "utf-8"));`

Those other two snippets you quoted look good as-is.

**Review by petermetz — CHANGES_REQUESTED** [review]
@aldousalvarez => https://github.com/hyperledger/cactus/pull/2164#discussion_r1023184730

**Comment by aldousalvarez** [comment]
@petermetz already done it with the latest [commit.](https://github.com/hyperledger/cactus/pull/2164/commits/01baf2aabe20e755501393bf46442ac0a3b2e3a5) I returned it all back on to the main function and now I created a variable for PROJECT_DIR + LERNA_JSON with   
const LERNA_JSON_DIR = PROJECT_DIR + LERNA_JSON; and I also created a console.log for it. Apologies as well for my confusion

**Comment by petermetz** [comment]
Suggested edit:
```diff
diff --git a/tools/sync-npm-deps-to-tsc-projects.ts b/tools/sync-npm-deps-to-tsc-projects.ts
index 93024ae2..79465bee 100644
--- a/tools/sync-npm-deps-to-tsc-projects.ts
+++ b/tools/sync-npm-deps-to-tsc-projects.ts
@@ -24,9 +24,10 @@ const main = async (argv: string[], env: NodeJS.ProcessEnv) => {
   const PROJECT_DIR = path.join(SCRIPT_DIR, "../");
   console.log(`SCRIPT_DIR=${SCRIPT_DIR}`);
   console.log(`PROJECT_DIR=${PROJECT_DIR}`);
-  const lernaJson = JSON.parse(
-    await readFile(PROJECT_DIR + LERNA_JSON, "utf-8"),
-  );
+
+  const lernaJsonStr = await readFile(PROJECT_DIR + LERNA_JSON, "utf-8");
+  const lernaJson = JSON.parse(lernaJsonStr);
+
   const pkgJsonGlobPatterns = lernaJson.packages.map((it: string) =>
     "./".concat(it).concat(`/${PACKAGE_JSON}`),
   );

```

**Review by petermetz — APPROVED** [review]
@aldousalvarez LGTM, thank you for the updates!
