### PR TITLE
fix(cmd-api-server): enable version selection in plugins

### LINKED ISSUE #839: fix(keychain-memory): Cannot find module "uuid"
**Describe the bug**

When I try to use the docker image of api-server and I pass as ENV the keychain-memory I can't use it.

**To Reproduce**

1.- Run the follow command:
```sh
 DOCKER_BUILDKIT=1 docker build --build-arg NPM_PKG_VERSION=fix-quorum-contract-types -f ./packages/cactus-cmd-api-server/Dockerfile . -t cas -t cactus-api-server
```

2.- Run the follow command:
```sh
 docker run \
    --rm \
    --publish 3000:3000 \
    --publish 4000:4000 \
    --env PLUGINS='[
    {
        "packageName": "@hyperledger/cactus-plugin-keychain-memory",
        "type": "org.hyperledger.cactus.plugin_import_type.LOCAL",
        "options": {
            "keychainId": "some-unique-keychain-id",
            "instanceId": "some-unique-instance-id"
        }
    },
    {
        "packageName": "@hyperledger/cactus-plugin-ledger-connector-besu",
        "type": "org.hyperledger.cactus.plugin_import_type.LOCAL",
        "options": {
            "rpcApiHttpHost": "http://localhost:8545",
            "instanceId": "some-unique-besu-connector-instance-id"
        }
    }
]' \
cas
```
**Logs/Stack traces**
``` sh
[2021-04-22T16:09:05.467Z] INFO (config-service): Configuration validation OK.
[2021-04-22T16:09:05.469Z] INFO (api-server): Setting tls.DEFAULT_MAX_VERSION to TLSv1.3...
[2021-04-22T16:09:05.469Z] INFO (api-server): wwwRoot: /usr/src/app/node_modules/@hyperledger/cactus-cockpit/www/
[2021-04-22T16:09:05.469Z] INFO (api-server): resolvedWwwRoot: /usr/src/app/node_modules/@hyperledger/cactus-cockpit/www
[2021-04-22T16:09:05.469Z] INFO (api-server): resolvedIndexHtml: /usr/src/app/node_modules/@hyperledger/cactus-cockpit/www/index.html
[2021-04-22T16:09:05.475Z] INFO (api-server): Cactus Cockpit net.AddressInfo { address: '0.0.0.0', family: 'IPv4', port: 3000 }
[2021-04-22T16:09:05.476Z] INFO (api-server): getOrInitPluginRegistry() initializing a new one...
[2021-04-22T16:09:05.476Z] INFO (api-server): Instantiated empty registry, invoking plugin factories...
[2021-04-22T16:09:05.476Z] INFO (api-server): Creating plugin from package: @hyperledger/cactus-plugin-keychain-memory {
  keychainId: 'some-unique-keychain-id',
  instanceId: 'some-unique-instance-id'
}
[2021-04-22T16:09:05.477Z] INFO (api-server): Installing @hyperledger/cactus-plugin-keychain-memory for plugin import {
  packageName: '@hyperledger/cactus-plugin-keychain-memory',
  type: 'org.hyperledger.cactus.plugin_import_type.LOCAL',
  options: {
    keychainId: 'some-unique-keychain-id',
    instanceId: 'some-unique-instance-id'
  }
}

added 4 packages, and removed 323 packages in 14s
[2021-04-22T16:09:18.713Z] INFO (api-server): Installed @hyperledger/cactus-plugin-keychain-memory OK undefined
[2021-04-22T16:09:18.728Z] ERROR (api-server): Failed to start ApiServer: Error: Cannot find module 'uuid'
Require stack:
- /usr/src/app/node_modules/@hyperledger/cactus-plugin-keychain-memory/dist/lib/main/typescript/plugin-factory-keychain.js
- /usr/src/app/node_modules/@hyperledger/cactus-plugin-keychain-memory/dist/lib/main/typescript/public-api.js
- /usr/src/app/node_modules/@hyperledger/cactus-plugin-keychain-memory/dist/lib/main/typescript/index.js
- /usr/src/app/node_modules/@hyperledger/cactus-cmd-api-server/dist/lib/main/typescript/api-server.js
- /usr/src/app/node_modules/@hyperledger/cactus-cmd-api-server/dist/lib/main/typescript/cmd/cactus-api.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/src/app/node_modules/@hyperledger/cactus-plugin-keychain-memory/dist/lib/main/typescript/plugin-factory-keychain.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
[2021-04-22T16:09:18.729Z] ERROR (api-server): Attempting shutdown...
[2021-04-22T16:09:18.729Z] INFO (api-server): Shutting down API server ...
[2021-04-22T16:09:18.729Z] INFO (api-server): getOrInitPluginRegistry() initializing a new one...
[2021-04-22T16:09:18.729Z] INFO (api-server): Instantiated empty registry, invoking plugin factories...
[2021-04-22T16:09:18.729Z] INFO (api-server): Creating plugin from package: @hyperledger/cactus-plugin-keychain-memory {
  keychainId: 'some-unique-keychain-id',
  instanceId: 'some-unique-instance-id'
}
[2021-04-22T16:09:18.729Z] INFO (api-server): Installing @hyperledger/cactus-plugin-keychain-memory for plugin import {
  packageName: '@hyperledger/cactus-plugin-keychain-memory',
  type: 'org.hyperledger.cactus.plugin_import_type.LOCAL',
  options: {
    keychainId: 'some-unique-keychain-id',
    instanceId: 'some-unique-instance-id'
  }
}

up to date in 14s
[2021-04-22T16:09:19.015Z] INFO (api-server): Installed @hyperledger/cactus-plugin-keychain-memory OK undefined
[2021-04-22T16:09:19.016Z] ERROR (cactus-api): Cactus API server crashed:  Error: Cannot find module 'uuid'
Require stack:
- /usr/src/app/node_modules/@hyperledger/cactus-plugin-keychain-memory/dist/lib/main/typescript/plugin-factory-keychain.js
- /usr/src/app/node_modules/@hyperledger/cactus-plugin-keychain-memory/dist/lib/main/typescript/public-api.js
- /usr/src/app/node_modules/@hyperledger/cactus-plugin-keychain-memory/dist/lib/main/typescript/index.js
- /usr/src/app/node_modules/@hyperledger/cactus-cmd-api-server/dist/lib/main/typescript/api-server.js
- /usr/src/app/node_modules/@hyperledger/cactus-cmd-api-server/dist/lib/main/typescript/cmd/cactus-api.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/src/app/node_modules/@hyperledger/cactus-plugin-keychain-memory/dist/lib/main/typescript/plugin-factory-keychain.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/src/app/node_modules/@hyperledger/cactus-plugin-keychain-memory/dist/lib/main/typescript/plugin-factory-keychain.js',
    '/usr/src/app/node_modules/@hyperledger/cactus-plugin-keychain-memory/dist/lib/main/typescript/public-api.js',
    '/usr/src/app/node_modules/@hyperledger/cactus-plugin-keychain-memory/dist/lib/main/typescript/index.js',
    '/usr/src/app/node_modules/@hyperledger/cactus-cmd-api-server/dist/lib/main/typescript/api-server.js',
    '/usr/src/app/node_modules/@hyperledger/cactus-cmd-api-server/dist/lib/main/typescript/cmd/cactus-api.js'
  ]
}
```

**Operating system name, version, build:**

```sh
$ printf "$(uname -srm)\n$(cat /etc/os-release)\n"
Darwin 19.6.0 x86_64
```

### PR DESCRIPTION
**Pull request by elenaizaguirre**
cactus-cmd-api-server can now import plugins specifying
the npm package version as a plugin option

cmd-api-server: add missing dependency bluebird

closes #839 and #840

Signed-off-by: Elena Izaguirre <e.izaguirre.equiza@accenture.com>

### CODE REVIEW

**Comment by elenaizaguirre** [comment]
@petermetz Finally I added bluebird dependency in this PR instead of the Quorum one because I thought it was better join cmd-api-server changes

**Review by takeutak — APPROVED** [review]

File: packages/cactus-cmd-api-server/src/main/typescript/api-server.ts [hunk 1]
```diff
@@ -326,6 +326,11 @@ export class ApiServer {
 
     const instanceId = pluginImport.options.instanceId;
     const pluginPackageDir = path.join(this.pluginsPath, instanceId);
+    const pluginVersion = // version of the npm package
```
Comment (petermetz) [inline packages/cactus-cmd-api-server/src/main/typescript/api-server.ts:329]: @elenaizaguirre 

Would this work here?

```suggestion
const pluginVersion = pluginImport.options.version ? "@".concat(pluginImport.options.version) : "";
```

File: packages/cactus-test-cmd-api-server/src/test/typescript/integration/plugin-import-with-npm-install.test.ts [hunk 2]
```diff
@@ -56,6 +56,7 @@ test("can instal plugins at runtime based on imports", async (t: Test) => {
       options: {
         instanceId: uuidv4(),
         keychainId: uuidv4(),
+        version: "0.9.0",
```
Comment (petermetz) [inline packages/cactus-test-cmd-api-server/src/test/typescript/integration/plugin-import-with-npm-install.test.ts:59]: @elenaizaguirre Can you add a test assertion that verifies if this particular version has been installed? You can parse the package.json file on the file-system where the plugin was installed and then check for strict equality between the version inside the package.json and what you declared here

**Review by petermetz — CHANGES_REQUESTED** [review]

File: packages/cactus-cmd-api-server/src/main/typescript/api-server.ts (hunk 1 above)
Comment (elenaizaguirre) [reply packages/cactus-cmd-api-server/src/main/typescript/api-server.ts:329]: @petermetz You're right, I thought that the condition would return true if the version was initialized even if it was an empty string

File: packages/cactus-test-cmd-api-server/src/test/typescript/integration/plugin-import-with-npm-install.test.ts (hunk 2 above)
Comment (elenaizaguirre) [reply packages/cactus-test-cmd-api-server/src/test/typescript/integration/plugin-import-with-npm-install.test.ts]: @petermetz Done, I added `--save-exact` flag to api-server.ts installation command. I have created another independent test for this and have reverted the others.

File: packages/cactus-cmd-api-server/src/main/typescript/api-server.ts (hunk 1 above)
Comment (petermetz) [reply packages/cactus-cmd-api-server/src/main/typescript/api-server.ts]: @elenaizaguirre I agree with your initial intuition :-) Javascript treats empty strings also as falsy values for some reason which we can exploit here to our advantage.

File: packages/cactus-test-cmd-api-server/src/test/typescript/integration/plugin-import-with-npm-install.test.ts (hunk 2 above)
Comment (petermetz) [reply packages/cactus-test-cmd-api-server/src/test/typescript/integration/plugin-import-with-npm-install.test.ts]: @elenaizaguirre Thank you for adjusting! 

One small nit-pick: It can be done without the `--save-exact` option if you parse the package.json of the installed plugin package instead of the project level package.json:
Meaning that when you run the install, it creates two package.json files, one as `./package.json` (relative to the plugins folder) and this is the one you are parsing now, but there's a second one under `./node_modules/@hyperledger/cactus-some-plugin-package/package.json`

If you parse the second file and check the `"version"` property it should have the expected `0.9.0` there and this way you don't need the save-exact option which is a minor thing but I'm concerned about using it due to unforeseen side-effects that it may cause (remember how much trouble we had with the npm installation mechanism already)

**Review by petermetz — APPROVED** [review]
@elenaizaguirre Reminder to hit 're-request review' when you want it to be reviewed again.
Marking the comments as 'resolved' doesn't do the same (I agree that it probably should though)

**Comment by elenaizaguirre** [comment]
> @elenaizaguirre Reminder to hit 're-request review' when you want it to be reviewed again. Marking the comments as 'resolved' doesn't do the same (I agree that it probably should though)

I'll keep it in mind!

**Comment by petermetz** [comment]
@elenaizaguirre I think the second one you'll have to close manually now that the PR has been merged in the meantime.
For the future: Yes please, however many issues are being closed by a PR, link all of them to it, it's fine if sometimes we accidentally open issues that end up being duplicates like that.
